const fruits = ["apple", "banana" , "orange"]
console.log(fruits)
fruits.push("grape" , "pear")
console.log(fruits)
fruits.pop()
console.log(fruits)
fruits.unshift("kiwi")
console.log(fruits)
fruits.shift()
console.log(fruits)